# railway.toml

name = "Battle Jawn"

[env.production]

build = "cd frontend && npm install && npm run build && npm run dev && npm run backend-build && npm run backend-dev"
public = "frontend/build"

[build]
root = "battlejawn/backend"
artifact = "backend/target/Battle-Jawn-1.0.0.jar"
