spring:
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    initialization-mode: always
    testWhileIdle: true
    validationQuery: SELECT 1

security.jwt.token.secret-key: ${PROD_SECRET_KEY}